[package]
name = "crust-core"
version = "0.1.0"
edition = { workspace = true }
license-file = { workspace = true }

[lib]
name = "crust_core"
path = "src/lib.rs"

[dependencies]
utils = { path = "../utils" }
rand = "0.9.0"
image = { version = "0.25.6", default-features = false, features = ["png"] }
rayon = "1.10.0"
serde.workspace = true
ron = "0.10.1"
obj-rs = "0.7.4"
indicatif = "0.17.11"
once_cell = "1.21.3"
ogawa-rs = { git = "https://github.com/doubleailes/ogawa-rs" }
glam.workspace = true
tracing.workspace = true
exr.workspace = true



[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "integrator"
harness = false
