#!/usr/bin/env python3
"""Generate a many-light stress scene: a field of N small coloured bulbs
(default 1,000,000) hovering over a floor, seen from a low grazing camera.

Two modes, because crust imports UsdLux lights only from the main stage walk
(a light inside a native-instance or PointInstancer prototype is not a light
entry; see openspec/specs/lighting/spec.md, Known gaps):

  --mode lights     (default) one SphereLight prim per bulb. Every bulb is a
                    real light-list entry, so NEE and light selection
                    (CRUST_LIGHT_SELECTION / power / uniform / learned) see all
                    N of them. ~150 bytes of text per light (~150 MB at 1M).

  --mode instanced  one PointInstancer placing a tiny emissive sphere N
                    times. One shared prototype, cheap to import, but the
                    bulbs are emissive geometry, reached by BSDF bounces
                    only, so the floor lighting is far noisier. One RectLight
                    keeps the floor readable.

Layout (Y up): bulbs on a jittered SIDE x SIDE grid (SIDE = ceil(sqrt(N)))
SPACING apart -- 200 x 200 units at 1M -- at heights 0.3-1.5 over the floor.
The density is the same at every N, so a small N previews the 1M look and
exposure. Colours cycle through hue, so the floor shows coloured pools.

Usage: gen_million_lights.py [-n N] [--mode lights|instanced] [out.usda|out.usdc]
A `.usdc` output is written as text and converted with the `pxr` module
(`pip install usd-core`). Prefer it for --mode lights at 1M: crust's openusd
reader holds about half the memory for a crate file (~10 KB per light, against
~21 KB for the same scene as text).
The scene is deliberately NOT checked in.
"""

import argparse
import colorsys
import math
import os
import random

SPACING = 0.2      # grid step between bulbs
INTENSITY = 0.035  # per bulb; with `normalize`, power = pi * intensity
RADIUS = 0.03      # bulb radius
SEED = 7


def bulbs(n):
    side = math.ceil(math.sqrt(n))
    step = SPACING
    field = side * step
    rng = random.Random(SEED)
    for i in range(n):
        r, c = divmod(i, side)
        x = -field / 2 + (c + 0.5 + rng.uniform(-0.35, 0.35)) * step
        z = -field / 2 + (r + 0.5 + rng.uniform(-0.35, 0.35)) * step
        y = rng.uniform(0.3, 1.5)
        hue = rng.random()
        col = colorsys.hsv_to_rgb(hue, 0.65, 1.0)
        yield (x, y, z), col


def header(f, n, mode):
    field = math.ceil(math.sqrt(n)) * SPACING
    f.write('#usda 1.0\n(\n'
            f'    doc = "{n} lights ({mode}), generated by scripts/gen_million_lights.py"\n'
            '    defaultPrim = "World"\n    upAxis = "Y"\n'
            '    metersPerUnit = 1\n)\n\n')
    f.write('def Xform "World"\n{\n')
    # Low, grazing view along the field: the near bulbs are resolved, the far
    # ones blur into a carpet of colour.
    f.write('    def Camera "Cam"\n    {\n'
            '        float focalLength = 24\n'
            '        float horizontalAperture = 36\n'
            '        float verticalAperture = 20.25\n'
            '        float2 clippingRange = (0.01, 10000)\n'
            f'        double3 xformOp:translate = (0, 4, {field / 2 + 2:g})\n'
            '        float xformOp:rotateX = -9\n'
            '        uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateX"]\n'
            '    }\n\n')
    f.write('    def Scope "Looks"\n    {\n'
            '        def Material "Floor"\n        {\n'
            '            token outputs:surface.connect = </World/Looks/Floor/Shader.outputs:surface>\n'
            '            def Shader "Shader"\n            {\n'
            '                uniform token info:id = "UsdPreviewSurface"\n'
            '                color3f inputs:diffuseColor = (0.6, 0.6, 0.6)\n'
            '                float inputs:roughness = 0.35\n'
            '                token outputs:surface\n'
            '            }\n        }\n')
    if mode == 'instanced':
        # The same power per bulb as `--mode lights`: a normalized light's
        # radiance is its intensity over its area.
        bulb_l = INTENSITY / (4 * math.pi * RADIUS * RADIUS)
        f.write('        def Material "Bulb"\n        {\n'
                '            token outputs:surface.connect = </World/Looks/Bulb/Shader.outputs:surface>\n'
                '            def Shader "Shader"\n            {\n'
                '                uniform token info:id = "UsdPreviewSurface"\n'
                '                color3f inputs:diffuseColor = (0, 0, 0)\n'
                f'                color3f inputs:emissiveColor = ({bulb_l:.3g}, {bulb_l * 0.85:.3g}, {bulb_l * 0.65:.3g})\n'
                '                token outputs:surface\n'
                '            }\n        }\n')
    f.write('    }\n\n')
    h = field * 0.6 + 5
    f.write('    def Mesh "Floor" (prepend apiSchemas = ["MaterialBindingAPI"])\n    {\n'
            '        uniform token subdivisionScheme = "none"\n'
            '        rel material:binding = </World/Looks/Floor>\n'
            '        int[] faceVertexCounts = [4]\n'
            '        int[] faceVertexIndices = [0, 1, 2, 3]\n'
            f'        point3f[] points = [(-{h}, 0, -{h}), (-{h}, 0, {h}), ({h}, 0, {h}), ({h}, 0, -{h})]\n'
            '    }\n\n')


def write_lights(f, n, visible):
    # Shared settings sit on every prim: an `inherits` arc per light would
    # cost a composition lookup each, which is the importer's bottleneck at
    # this count. `normalize` makes `intensity` proportional to power, so the
    # bulb radius does not change the exposure.
    f.write('    def Xform "Lights"\n    {\n')
    for i, ((x, y, z), (r, g, b)) in enumerate(bulbs(n)):
        f.write(f'        def SphereLight "L{i}" {{\n'
                f'            float inputs:radius = {RADIUS}\n'
                '            bool inputs:normalize = 1\n'
                f'            float inputs:intensity = {INTENSITY}\n'
                f'            color3f inputs:color = ({r:.3f}, {g:.3f}, {b:.3f})\n'
                f'            double3 xformOp:translate = ({x:.3f}, {y:.3f}, {z:.3f})\n'
                '            uniform token[] xformOpOrder = ["xformOp:translate"]\n'
                + ('            custom bool crust:light:cameraVisible = 1\n' if visible else '')
                + '        }\n')
    f.write('    }\n')


def write_instanced(f, n, _visible):
    f.write('    def RectLight "Key"\n    {\n'
            '        float inputs:width = 40\n        float inputs:height = 40\n'
            '        float inputs:intensity = 0.15\n'
            '        double3 xformOp:translate = (0, 30, 0)\n'
            '        float xformOp:rotateX = -90\n'
            '        uniform token[] xformOpOrder = ["xformOp:translate", "xformOp:rotateX"]\n'
            '    }\n\n')
    f.write('    def PointInstancer "Bulbs"\n    {\n'
            '        rel prototypes = [</World/Bulbs/Proto/Bulb>]\n')
    f.write(f'        int[] protoIndices = [{", ".join(["0"] * n)}]\n')
    f.write('        point3f[] positions = [')
    f.write(', '.join(f'({x:.3f}, {y:.3f}, {z:.3f})' for (x, y, z), _ in bulbs(n)))
    f.write(']\n')
    f.write('        def Scope "Proto"\n        {\n'
            '            def Sphere "Bulb" (prepend apiSchemas = ["MaterialBindingAPI"])\n            {\n'
            f'                double radius = {RADIUS}\n'
            '                rel material:binding = </World/Looks/Bulb>\n'
            '            }\n        }\n    }\n')


def main():
    ap = argparse.ArgumentParser(description=__doc__.split('\n')[0])
    ap.add_argument('out', nargs='?', default='million_lights.usda')
    ap.add_argument('-n', type=int, default=1_000_000, help='number of bulbs')
    ap.add_argument('--mode', choices=['lights', 'instanced'], default='lights')
    ap.add_argument('--hide-bulbs', action='store_true',
                    help='--mode lights: leave the bulbs hidden from camera '
                         'rays, crust\'s default for lights (otherwise each '
                         'authors crust:light:cameraVisible, ~+1.5%% memory)')
    a = ap.parse_args()
    crate = a.out.endswith('.usdc')
    text = a.out[:-1] + 'a' if crate else a.out
    with open(text, 'w') as f:
        header(f, a.n, a.mode)
        (write_lights if a.mode == 'lights' else write_instanced)(f, a.n, not a.hide_bulbs)
        f.write('}\n\n')
        f.write('def Scope "Render"\n{\n    def RenderSettings "settings"\n    {\n'
                '        rel camera = </World/Cam>\n'
                '        int2 resolution = (960, 540)\n'
                '    }\n}\n')
    if crate:
        from pxr import Usd
        Usd.Stage.Open(text).Export(a.out)
        os.remove(text)
    print(f'wrote {a.out}: {a.n} bulbs, mode {a.mode}')


if __name__ == '__main__':
    main()
