#!/usr/bin/env python3
"""Convert BSDL's baked dielectric reflection table to a Rust `const`.

The table is the directional-throughput filter `1 − E_R(cosθo)` of a rough
dielectric that reflects only (BSDL `mtx::DielectricReflFront`), which the
MaterialX closure evaluator uses as `T_top` when a dielectric sits in the top of
a `layer`. It is what NVIDIA Typhoon uses by default
(`ty:dielectricLayerThroughputMode = "bsdl"`).

Regenerating it (BSD-3-Clause source, Copyright Contributors to the Open
Shading Language project; BSDL as vendored in NVIDIA's OpenUSD `typhoon/main`
at 70c45e8, `pxr/imaging/plugin/hdEmbree/renderer/materials/BSDL`, which needs
Imath 3.x):

    g++ -std=c++17 -O2 -DNDEBUG -I BSDL/include -I <imath>/include/Imath \\
        -I <imath>/include BSDL/src/genluts.cpp -pthread -o genluts
    mkdir -p out/SPI out/MTX && ./genluts out          # ~1 min on 4 cores
    scripts/tables/bsdl_luts_to_rust.py out/MTX/bsdf_dielectric_reflfront_luts.h \\
        > crates/crust-core/src/material/closure/bsdl_tables.rs

The baked values are deterministic (hashed QMC seeds); the output of this recipe
matches Typhoon's own `dielectricReflFrontLut.h` bit for bit.
"""
import re
import sys

import numpy as np

NF, NR, NC = 32, 16, 16


def main(path):
    text = open(path).read()
    body = text[text.index("energy = {{"):]
    vals = [float(v) for v in re.findall(r"-?\d+\.\d*(?:e-?\d+)?(?=f)", body)]
    if len(vals) != NF * NR * NC:
        raise SystemExit(f"expected {NF * NR * NC} values, found {len(vals)}")
    out = [
        "//! BSDL's rough-dielectric reflection throughput table, `1 − E_R(cosθo)`.",
        "//!",
        "//! Generated by `scripts/tables/bsdl_luts_to_rust.py` from BSDL's",
        "//! `genluts` (`mtx::DielectricReflFront`). BSDL is BSD-3-Clause,",
        "//! Copyright Contributors to the Open Shading Language project; see",
        "//! `THIRD-PARTY.md`. Do not edit by hand.",
        "//!",
        "//! Layout `[ior][roughness][cosθo]`: 32 IOR steps at index",
        "//! `√((η − 1.001)/(5 − 1.001))`, 16 perceptual-roughness steps over [0, 1],",
        "//! 16 cosines `i/15` (the first floored at 1e-6).",
        "",
        "pub(super) const NF: usize = 32;",
        "pub(super) const NR: usize = 16;",
        "pub(super) const NC: usize = 16;",
        "",
        "#[rustfmt::skip]",
        f"pub(super) static DIELECTRIC_REFL_FRONT: [f32; {NF * NR * NC}] = [",
    ]
    for row in range(NF * NR):
        cells = vals[row * NC:(row + 1) * NC]
        # The shortest literal that round-trips to the same `f32` bits.
        out.append("    " + " ".join(f"{np.format_float_positional(np.float32(v), unique=True, trim='0')}," for v in cells))
    out.append("];")
    print("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
