#!/usr/bin/env python3
"""Convert Disney's Zeltner sheen LTC table to a Rust `static`.

The table is the "Volume" fit of Zeltner, Burley and Chiang, "Practical
Multiple-Scattering Sheen Using Linearly Transformed Cosines" (2022): for each
(sheen roughness α, cos θ_o) on a 32 × 32 grid, the inverse LTC coefficients
(a⁻¹, b⁻¹) and the lobe's directional albedo R. It is the fit Adobe's OpenPBR
reference uses for fuzz (`impl/data/openpbr_ltc_data.h`), value for value.

Regenerating it (Apache-2.0 source by Tizian Zeltner, Brent Burley and Matt
Jen-Yuan Chiang; see `THIRD-PARTY.md`):

    git clone https://github.com/tizian/ltc-sheen
    scripts/tables/ltc_sheen_to_rust.py ltc-sheen/pbrt-v3/src/materials/sheenltc.cpp \\
        [--check <openpbr-bsdf>/impl/data/openpbr_ltc_data.h] \\
        > crates/crust-core/src/material/ltc_sheen_table.rs

`--check` refuses to write unless Adobe's copy holds the same 3072 values.
"""
import argparse
import re
import sys

N = 32


def volume_table(path):
    text = open(path).read()
    start = text.index("SheenLTC::_ltcParamTableVolume[32][32] = {")
    end = text.index("SheenLTC::_ltcParamTableApprox", start)
    vals = re.findall(r"-?\d+\.\d+", text[start:end])
    if len(vals) != N * N * 3:
        raise SystemExit(f"expected {N * N * 3} values, found {len(vals)}")
    return vals


def adobe_table(path):
    text = open(path).read()
    vals = re.findall(r"-?\d+\.\d+", text[text.index("vec3("):])
    return vals[: N * N * 3]


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("sheenltc_cpp")
    ap.add_argument("--check", metavar="OPENPBR_LTC_DATA_H")
    args = ap.parse_args()

    vals = volume_table(args.sheenltc_cpp)
    if args.check:
        other = adobe_table(args.check)
        diff = [i for i, (a, b) in enumerate(zip(vals, other)) if float(a) != float(b)]
        if len(other) != len(vals) or diff:
            raise SystemExit(f"Adobe's table differs at {len(diff)} values (first: {diff[:5]})")

    out = [
        "//! Disney's Zeltner sheen LTC table, the \"Volume\" fit.",
        "//!",
        "//! Generated by `scripts/tables/ltc_sheen_to_rust.py` from",
        "//! `tizian/ltc-sheen` (`pbrt-v3/src/materials/sheenltc.cpp`, Apache-2.0, by",
        "//! Tizian Zeltner, Brent Burley and Matt Jen-Yuan Chiang; see `THIRD-PARTY.md`).",
        "//! Adobe's OpenPBR reference ships the same values. Do not edit by hand.",
        "//!",
        "//! Layout `[α][cosθo]`, both on 32 steps over [0, 1]; each entry is",
        "//! `[a⁻¹, b⁻¹, R]`: the inverse LTC coefficients and the directional albedo.",
        "",
        f"pub(crate) const N: usize = {N};",
        "",
        "// Fitted data: an entry that happens to read like a constant (0.69314) is not one.",
        "#[allow(clippy::approx_constant)]",
        "#[rustfmt::skip]",
        f"pub(crate) static LTC_SHEEN_VOLUME: [[f32; 3]; {N * N}] = [",
    ]
    for row in range(N):
        out.append(f"    // α = {row}/{N - 1}")
        for col0 in range(0, N, 4):
            cells = []
            for col in range(col0, col0 + 4):
                i = (row * N + col) * 3
                cells.append(f"[{vals[i]}, {vals[i + 1]}, {vals[i + 2]}],")
            out.append("    " + " ".join(cells))
    out.append("];")
    sys.stdout.write("\n".join(out) + "\n")


if __name__ == "__main__":
    main()
